language: Java

jdk:
  - oraclejdk11
  
before_install:
  - chmod +x mvnw
  
env:
  SQL_URL: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
  HIBERNATE_DIALECT: org:hibernate:dialect:H2Dialect
  SQL_DRIVER: org:h2:Driver
